runtime: python
env: flex
entrypoint: gunicorn -b :$PORT breed.wsgi

runtime_config:
  python_version: 3


env_variables:
  SECRET_KEY: '=v$!wc)t5nz610g-&t%y3krl*+yjju_ta_zy(e(!!!q5#5d)nm'


  DB_HOST: 'breed-216612:us-central1:artisanisland-db'
  DB_PORT: '5432'
  DB_NAME: 'artisanisland-db'
  DB_USER: 'postgres'
  DB_PASSWORD: 'hublot@1729'
