runtime: python
env: flex
entrypoint: gunicorn -b :$PORT breed.wsgi

runtime_config:
  python_version: 3


env_variables:
  SECRET_KEY: 'lv$!wc)t5nz610g-&t%y3krl*+yjju_ta_zy(e(!!!q5#5d)nm#97&h=w'

  DEBUG: 'False'

  DB_HOST: '/cloudsql/breed-216612:breed-216612:us-central1:artisanisland-db'
  DB_NAME: 'artisanisland-db'
  DB_USER: 'postgres'
  PASSWORD: 'hublot@1729'
  PORT: '5432'

  STATIC_URL: 'https://console.cloud.google.com/storage/{}/'.format(GS_BUCKET_NAME)
