from decouple import config

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT breed.wsgi

runtime_config:
  python_version: 3


env_variables:
  SECRET_KEY = config('SECRET_KEY')

  DEBUG = False

  HOST = config('DB_HOST')
  NAME = config('DB_NAME')
  USER = config('DB_USER')
  PASSWORD = config('DB_PASSWORD')
  PORT = config('DB_PORT')

  STATIC_URL = 'https://console.cloud.google.com/storage/{}/'.format(GS_BUCKET_NAME)

  handlers:
  - url: /static
  static_dir: static

  GS_KEY_ID=b1eced6b8544250694b7efff9612749d3c14ddfe
  GS_BUCKET_NAME=breed-216612
  GC_PROJECT_ID=breed-216612
