runtime: python
env: flex
entrypoint: gunicorn -b :$PORT breed.wsgi

runtime_config:
  python_version: 3


env_variables:
  SECRET_KEY=lv$!wc)t5nz610g-&t%y3krl*+yjju_ta_zy(e(!!!q5#5d)nm#97&h=w

  DB_HOST=localhost
  DB_NAME=artisanisland-db
  DB_USER=postgres
  DB_PASSWORD=hublot@1729
  DB_PORT=5432

  GOOGLE_APP_CREDENTIALS=/Users/macintosh/Downloads/breed-b1eced6b8544.json
  GS_KEY_ID=b1eced6b8544250694b7efff9612749d3c14ddfe
  GS_BUCKET_NAME=breed-216612
  GC_PROJECT_ID=breed-216612
