# Generated by Django 2.1 on 2018-09-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbreed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
