# Generated by Django 2.1 on 2018-09-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbreed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
