# Generated by Django 2.1 on 2018-09-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbreed', '0002_artisan_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='detail',
            field=models.TextField(max_length=2500),
        ),
    ]
